Repository TheCreators/BrawlBorne, pull requests merged in 2023-05, with the labels that each got.

#22 Add new weapons
  Assets/Materials/Bomb.physicMaterial
  Assets/Materials/Bomb.physicMaterial.meta
  Assets/Prefabs/Heroes.meta
  Assets/Prefabs/Heroes/Cube.prefab
  Assets/Prefabs/Heroes/Cube.prefab.meta
  Assets/Prefabs/Heroes/Player.prefab
  Assets/Prefabs/Heroes/Player.prefab.meta
  Assets/Prefabs/Projectiles.meta
  Assets/Prefabs/Projectiles/Bomb.prefab
  Assets/Prefabs/Projectiles/Bomb.prefab.meta
  Assets/Prefabs/Projectiles/DualGunBullet.prefab
  Assets/Prefabs/Projectiles/DualGunBullet.prefab.meta
  Assets/Prefabs/Projectiles/ShotgunBullet.prefab
  Assets/Prefabs/Projectiles/ShotgunBullet.prefab.meta
  Assets/Prefabs/Weapons.meta
  Assets/Prefabs/Weapons/Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Ballistic Gun.prefab.meta
  Assets/Prefabs/Weapons/Dual Gun.prefab
  Assets/Prefabs/Weapons/Dual Gun.prefab.meta
  Assets/Prefabs/Weapons/Knife.prefab
  Assets/Prefabs/Weapons/Knife.prefab.meta
  Assets/Prefabs/Weapons/Shot Gun.prefab
  Assets/Prefabs/Weapons/Shot Gun.prefab.meta
  Assets/Scenes/GoldenPlayground.unity
  Assets/Scripts/Combat.meta
  Assets/Scripts/Combat/Health.cs
  Assets/Scripts/Combat/Health.cs.meta
  Assets/Scripts/Combat/IDamageable.cs
  Assets/Scripts/Combat/IDamageable.cs.meta
  Assets/Scripts/Combat/Projectiles.meta
  Assets/Scripts/Combat/Projectiles/Bomb.cs
  Assets/Scripts/Combat/Projectiles/Bomb.cs.meta
  Assets/Scripts/Combat/Projectiles/Bullet.cs
  Assets/Scripts/Combat/Projectiles/Bullet.cs.meta
  Assets/Scripts/Combat/Projectiles/Projectile.cs
  Assets/Scripts/Combat/Projectiles/Projectile.cs.meta
  Assets/Scripts/Combat/Projectiles/RigidbodyProjectile.cs
  Assets/Scripts/Combat/Projectiles/RigidbodyProjectile.cs.meta
  Assets/Scripts/Combat/Weapons.meta
  Assets/Scripts/Combat/Weapons/BallisticGun.cs
  Assets/Scripts/Combat/Weapons/BallisticGun.cs.meta
  Assets/Scripts/Combat/Weapons/DualGun.cs
  Assets/Scripts/Combat/Weapons/DualGun.cs.meta
  Assets/Scripts/Combat/Weapons/Gun.cs
  Assets/Scripts/Combat/Weapons/Gun.cs.meta
  Assets/Scripts/Combat/Weapons/Knife.cs
  Assets/Scripts/Combat/Weapons/Knife.cs.meta
  Assets/Scripts/Combat/Weapons/ShotGun.cs
  Assets/Scripts/Combat/Weapons/ShotGun.cs.meta
  Assets/Scripts/Combat/Weapons/Weapon.cs
  Assets/Scripts/Combat/Weapons/Weapon.cs.meta
  Assets/Scripts/Guns/Bullet.cs
  Assets/Scripts/Guns/Gun.cs
  Assets/Scripts/Player/PlayerCombat.cs
  Assets/Scripts/Player/PlayerCombat.cs.meta
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/TagManager.asset
  README.md
Labels: feature

#24 Add flying ultimate
  Assets/PlayerInput.inputactions
  Assets/Scripts/Ultimates.meta
  Assets/Scripts/Ultimates/FlyingUltimate.cs
  Assets/Scripts/Ultimates/FlyingUltimate.cs.meta
Labels: feature

#35 Add ultimate cooldown
  Assets/Scripts/Ultimates/FlyingUltimate.cs
  Assets/Scripts/Ultimates/HealingUltimate.cs
  Assets/Scripts/Ultimates/SpeedUltimate.cs
  Assets/Scripts/Ultimates/Ultimate.cs
  Assets/Scripts/Ultimates/WeaponUpgradeUltimate.cs
Labels: feature

#36 Add event system and fix bots
  Assets/Events.meta
  Assets/Events/HeroAirborne.asset
  Assets/Events/HeroAirborne.asset.meta
  Assets/Events/HeroDied.asset
  Assets/Events/HeroDied.asset.meta
  Assets/Events/HeroJumped.asset
  Assets/Events/HeroJumped.asset.meta
  Assets/Events/HeroLand.asset
  Assets/Events/HeroLand.asset.meta
  Assets/Events/HeroMove.asset
  Assets/Events/HeroMove.asset.meta
  Assets/Events/HeroSneak.asset
  Assets/Events/HeroSneak.asset.meta
  Assets/Events/HeroStopMoving.asset
  Assets/Events/HeroStopMoving.asset.meta
  Assets/Events/HeroStopSneaking.asset
  Assets/Events/HeroStopSneaking.asset.meta
  Assets/Events/WeaponUsed.asset
  Assets/Events/WeaponUsed.asset.meta
  Assets/Prefabs/Heroes/Bot.prefab
  Assets/Prefabs/Heroes/Player.prefab
  Assets/Prefabs/HeroesPool.prefab
  Assets/Prefabs/ShootAt.prefab
  Assets/Prefabs/Weapons/Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Bat Gun.prefab
  Assets/Prefabs/Weapons/Dual Gun.prefab
  Assets/Prefabs/Weapons/Knife.prefab
  Assets/Prefabs/Weapons/Shot Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Dual Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Shot Gun.prefab
  Assets/Scenes/Empty.unity
  Assets/Scripts/Bot/BotCombat.cs
  Assets/Scripts/Bot/BotController.cs
  Assets/Scripts/Bot/BotMovement.cs
  Assets/Scripts/Bot/BotSensor.cs
  Assets/Scripts/Combat/Health.cs
  Assets/Scripts/Combat/ShootAt.cs
  Assets/Scripts/Combat/ShootAt.cs.meta
  Assets/Scripts/Combat/Weapons/DualGun.cs
  Assets/Scripts/Combat/Weapons/Weapon.cs
  Assets/Scripts/Events.meta
  Assets/Scripts/Events/CustomUnityEvent.cs
  Assets/Scripts/Events/CustomUnityEvent.cs.meta
  Assets/Scripts/Events/GameEvent.cs
  Assets/Scripts/Events/GameEvent.cs.meta
  Assets/Scripts/Events/GameEventListener.cs
  Assets/Scripts/Events/GameEventListener.cs.meta
  Assets/Scripts/Misc/GroundChecker.cs
  Assets/Scripts/Misc/Hero.cs
  Assets/Scripts/Misc/Hero.cs.meta
  Assets/Scripts/Misc/HeroesPool.cs
  Assets/Scripts/Player/PlayerJump.cs
  Assets/Scripts/Player/PlayerMovement.cs
  Assets/Scripts/Sound/FootstepsSound.cs
  Assets/Scripts/Sound/WeaponSound.cs
  Assets/Scripts/Ultimates/SpeedUltimate.cs
Labels: feature

#40 Add logic after death
  Assets/Prefabs/Heroes/Player.prefab
  Assets/Scenes/Game Over Scene.unity
  Assets/Scenes/Game Over Scene.unity.meta
  Assets/Scenes/GoldenPlayground.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Menu/MainMenu.cs
  Assets/Scripts/Misc/HeroesPool.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#38 Add crosshair and health bar.
  Assets/Events/HeroHealthChanged.asset
  Assets/Events/HeroHealthChanged.asset.meta
  Assets/Images/Crosshairs.meta
  Assets/Images/Crosshairs/Crosshair_04.png
  Assets/Images/Crosshairs/Crosshair_04.png.meta
  Assets/Images/Crosshairs/Crosshair_26.png
  Assets/Images/Crosshairs/Crosshair_26.png.meta
  Assets/Images/Crosshairs/Crosshair_27.png
  Assets/Images/Crosshairs/Crosshair_27.png.meta
  Assets/Images/HealthBar.png
  Assets/Images/HealthBar.png.meta
  Assets/Prefabs/Heroes/Bot.prefab
  Assets/Prefabs/Heroes/Cube.prefab
  Assets/Prefabs/Heroes/Player.prefab
  Assets/Prefabs/Weapons/Frisbee.prefab
  Assets/Prefabs/Weapons/Frisbee.prefab.meta
  Assets/Scenes/GoldenPlayground.unity
  Assets/Scripts/Combat/Health.cs
  Assets/Scripts/Hud.meta
  Assets/Scripts/Hud/HealthBar.cs
  Assets/Scripts/Hud/HealthBar.cs.meta
Labels: feature

#39 Add bot sounds and sound range
  Assets/Prefabs/Heroes/Bot.prefab
  Assets/Prefabs/Heroes/Player.prefab
  Assets/Scenes/Empty/NavMesh.asset
  Assets/Scripts/Bot/BotMovement.cs
Labels: bug, feature

#41 Win menu and sensitivity settings
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/Win Scene.unity
  Assets/Scenes/Win Scene.unity.meta
  Assets/Scripts/Menu/SettingsSaver.cs
  Assets/Scripts/Misc/HeroesPool.cs
  Assets/Scripts/Player/MouseRotation.cs
  Assets/Scripts/Ultimates/FlyingUltimate.cs
  Assets/Scripts/Ultimates/SpeedUltimate.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#42 Heroes spawn
  Assets/Prefabs/Environment/Wall.prefab
  Assets/Scenes/BattleField.unity
  Assets/Scripts/Battlefield/BattleFieldBuilder.cs
  Assets/Scripts/Battlefield/BattleFieldGenerator.cs
  Assets/Scripts/Misc/HeroesPool.cs
Labels: bug

#44 feat: generated bots are random
  Assets/Prefabs/BattleFieldBuilder.prefab
  Assets/Prefabs/Heroes/Bots/Dinomike Bot.prefab
  Assets/Prefabs/Heroes/Bots/Mortis Bot.prefab
  Assets/Prefabs/Heroes/Bots/Poko Bot.prefab
  Assets/Prefabs/Heroes/Bots/Shelly Bot.prefab
  Assets/Scenes/BattleField.unity
  Assets/Scripts/Battlefield/BattleFieldBuilder.cs
Labels: feature

#47 fix: fixed bots spawn
  Assets/Scripts/Battlefield/BattleFieldGenerator.cs
Labels: bug

#49 Fix HUD
  Assets/Prefabs/HUD.prefab
  Assets/Scenes/CharacterChoice.unity
Labels: bug

#52 Add Post-Processing
  Assets/Prefabs/Heroes/Player.prefab
  Assets/Scenes/BattleField.unity
  Assets/Scenes/BattleField_Profiles.meta
  Assets/Scenes/BattleField_Profiles/Post-Process Volume Profile.asset
  Assets/Scenes/BattleField_Profiles/Post-Process Volume Profile.asset.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
Labels: feature

#53 Convert Ultimate to separate Object
  Assets/Prefabs/Ultimates.meta
  Assets/Prefabs/Ultimates/Flying Ultimate.prefab
  Assets/Prefabs/Ultimates/Flying Ultimate.prefab.meta
  Assets/Prefabs/Ultimates/Healing Ultimate.prefab
  Assets/Prefabs/Ultimates/Healing Ultimate.prefab.meta
  Assets/Prefabs/Ultimates/Speed Ultimate.prefab
  Assets/Prefabs/Ultimates/Speed Ultimate.prefab.meta
  Assets/Prefabs/Ultimates/Weapon Upgrade Ultimate.prefab
  Assets/Prefabs/Ultimates/Weapon Upgrade Ultimate.prefab.meta
  Assets/Scenes/Empty.unity
  Assets/Scripts/Bot/BotCombat.cs
  Assets/Scripts/Combat/Weapons/Weapon.cs
  Assets/Scripts/Player/PlayerCombat.cs
  Assets/Scripts/Ultimates/FlyingUltimate.cs
  Assets/Scripts/Ultimates/HealingUltimate.cs
  Assets/Scripts/Ultimates/SpeedUltimate.cs
  Assets/Scripts/Ultimates/Ultimate.cs
  Assets/Scripts/Ultimates/WeaponUpgradeUltimate.cs
Labels: bug, feature

#54 Add Null Check for Components
  Assets/Prefabs/Environment/Boost Crate.prefab
  Assets/Prefabs/Heroes/Characters/Bonni.prefab
  Assets/Prefabs/Heroes/Characters/Carl.prefab
  Assets/Prefabs/Heroes/Characters/Dinomike.prefab
  Assets/Prefabs/Heroes/Characters/Poko.prefab
  Assets/Scripts/Abilities/DashAbility.cs
  Assets/Scripts/Battlefield/BattleFieldBuilder.cs
  Assets/Scripts/Bot/BotCombat.cs
  Assets/Scripts/Bot/BotController.cs
  Assets/Scripts/Bot/BotMovement.cs
  Assets/Scripts/CharacterSelection/ButtonCharacterName.cs
  Assets/Scripts/CharacterSelection/CameraMovement.cs
  Assets/Scripts/Combat/Health.cs
  Assets/Scripts/Combat/Projectiles/Bomb.cs
  Assets/Scripts/Combat/Projectiles/Bullet.cs
  Assets/Scripts/Combat/Projectiles/RigidbodyProjectile.cs
  Assets/Scripts/Combat/Weapons/BallisticGun.cs
  Assets/Scripts/Combat/Weapons/Gun.cs
  Assets/Scripts/Combat/Weapons/Knife.cs
  Assets/Scripts/Environment/Crate.cs
  Assets/Scripts/Events/GameEventListener.cs
  Assets/Scripts/Hud/EnemiesLeftText.cs
  Assets/Scripts/Hud/HealthBar.cs
  Assets/Scripts/Menu/SettingsSaver.cs
  Assets/Scripts/Misc/ComponentExtensions.cs
  Assets/Scripts/Misc/ComponentExtensions.cs.meta
  Assets/Scripts/Misc/GroundChecker.cs
  Assets/Scripts/Misc/Hero.cs
  Assets/Scripts/Misc/HeroesPool.cs
  Assets/Scripts/Misc/TransformExtensions.cs
  Assets/Scripts/Misc/TransformExtensions.cs.meta
  Assets/Scripts/Player/AnimationStateController.cs
  Assets/Scripts/Player/PlayerCombat.cs
  Assets/Scripts/Player/PlayerJump.cs
  Assets/Scripts/Player/PlayerMovement.cs
  Assets/Scripts/Sound/FootstepsSound.cs
  Assets/Scripts/Sound/WeaponSound.cs
  Assets/Scripts/Ultimates/FlyingUltimate.cs
  Assets/Scripts/Ultimates/HealingUltimate.cs
  Assets/Scripts/Ultimates/SpeedUltimate.cs
  Assets/Scripts/Ultimates/Ultimate.cs
  Assets/Scripts/Ultimates/WeaponUpgradeUltimate.cs
Labels: feature

#57 Add Boost Damage Increase
  Assets/Prefabs/Projectiles/Bat Bullet.prefab
  Assets/Prefabs/Projectiles/Bomb.prefab
  Assets/Prefabs/Projectiles/Bullet.prefab
  Assets/Prefabs/Projectiles/Dual Gun Bullet.prefab
  Assets/Prefabs/Projectiles/Shot Gun Bullet.prefab
  Assets/Prefabs/Projectiles/Ultimate Bomb.prefab
  Assets/Prefabs/Projectiles/Unlimate Dual Gun Bullet.prefab
  Assets/Prefabs/Weapons/Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Bat Gun.prefab
  Assets/Prefabs/Weapons/Dual Gun.prefab
  Assets/Prefabs/Weapons/Knife.prefab
  Assets/Prefabs/Weapons/Shot Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Dual Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Shot Gun.prefab
  Assets/Scripts/Combat/Health.cs
  Assets/Scripts/Combat/Projectiles/Bomb.cs
  Assets/Scripts/Combat/Projectiles/Bullet.cs
  Assets/Scripts/Combat/Projectiles/Projectile.cs
  Assets/Scripts/Combat/Projectiles/RigidbodyProjectile.cs
  Assets/Scripts/Combat/Weapons/BallisticGun.cs
  Assets/Scripts/Combat/Weapons/BulletGun.cs
  Assets/Scripts/Combat/Weapons/BulletGun.cs.meta
  Assets/Scripts/Combat/Weapons/DualGun.cs
  Assets/Scripts/Combat/Weapons/Gun.cs
  Assets/Scripts/Combat/Weapons/Knife.cs
  Assets/Scripts/Combat/Weapons/ShotGun.cs
  Assets/Scripts/Combat/Weapons/Weapon.cs
  Assets/Scripts/Environment/Boost.cs
Labels: feature

#58 Spawn errors solve
  Assets/Prefabs/BattleField Builder.prefab
  Assets/Prefabs/Environment/Invisible Wall.prefab
  Assets/Prefabs/Environment/Invisible Wall.prefab.meta
  Assets/Scenes/BattleField.unity
  Assets/Scripts/Battlefield/BattleFieldBuilder.cs
  Assets/Scripts/Battlefield/BattleFieldGenerator.cs
Labels: bug, feature

#60 Fix texture to model's materials
  Assets/Models/Materials/Squeak 1.mat
  Assets/Models/Materials/Squeak 2.mat
  Assets/Models/Materials/character_mat.mat
  Assets/Models/Materials/dyno 2.mat
  Assets/Models/Materials/dyno.mat
Labels: bug

#62 Fix Melee and Bots
  Assets/Prefabs/Heroes/Bots/Bot.prefab
  Assets/Prefabs/Heroes/Bots/Dinomike Bot.prefab
  Assets/Scripts/Bot/BotCombat.cs
  Assets/Scripts/Bot/BotMovement.cs
  Assets/Scripts/Bot/BotSensor.cs
  Assets/Scripts/Combat/Weapons/BallisticGun.cs
  Assets/Scripts/Combat/Weapons/Weapon.cs
Labels: bug

#63 Add game UI
  Assets/Prefabs/HUD.prefab
  Assets/Prefabs/Heroes/Bots/Bot.prefab
  Assets/Prefabs/Heroes/Bots/Colt Bot.prefab
  Assets/Prefabs/Heroes/Bots/Dinomike Bot.prefab
  Assets/Prefabs/Heroes/Bots/Mortis Bot.prefab
  Assets/Prefabs/Heroes/Bots/Poko Bot.prefab
  Assets/Prefabs/Heroes/Bots/Shelly Bot.prefab
  Assets/Prefabs/Heroes/Characters/Colt.prefab
  Assets/Prefabs/Heroes/Characters/Dinomike.prefab
  Assets/Prefabs/Heroes/Characters/El Primo.prefab
  Assets/Prefabs/Heroes/Characters/Janet.prefab
  Assets/Prefabs/Heroes/Characters/Mortis.prefab
  Assets/Prefabs/Heroes/Characters/Player.prefab
  Assets/Prefabs/Heroes/Characters/Poko.prefab
  Assets/Prefabs/Heroes/Characters/Shelly.prefab
  Assets/Prefabs/Heroes/Characters/Squeak.prefab
  Assets/Prefabs/Heroes/HeroGameUI.prefab
  Assets/Prefabs/Heroes/HeroGameUI.prefab.meta
  Assets/Scenes/BattleField.unity
  Assets/Scripts/Combat/Projectiles/Bomb.cs
  Assets/Scripts/Combat/Projectiles/Bullet.cs
  Assets/Scripts/Combat/Projectiles/Projectile.cs
  Assets/Scripts/Combat/Weapons/BallisticGun.cs
  Assets/Scripts/Combat/Weapons/DualGun.cs
  Assets/Scripts/Combat/Weapons/Gun.cs
  Assets/Scripts/Combat/Weapons/ShotGun.cs
  Assets/Scripts/Hud/HealthBar.cs
Labels: bug, feature

#65 Balance stats
  Assets/Prefabs/Environment/Boost Crate.prefab
  Assets/Prefabs/Environment/Boost.prefab
  Assets/Prefabs/Heroes/Bots/Bot.prefab
  Assets/Prefabs/Heroes/Bots/Mortis Bot.prefab
  Assets/Prefabs/Heroes/Characters/Mortis.prefab
  Assets/Prefabs/Heroes/Characters/Player.prefab
  Assets/Prefabs/Ultimates/Healing Ultimate.prefab
  Assets/Prefabs/Ultimates/Speed Ultimate.prefab
  Assets/Prefabs/Weapons/Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Bat Gun.prefab
  Assets/Prefabs/Weapons/Dual Gun.prefab
  Assets/Prefabs/Weapons/Knife.prefab
  Assets/Prefabs/Weapons/Shot Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Ballistic Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Dual Gun.prefab
  Assets/Prefabs/Weapons/Ultimate Shot Gun.prefab
  Assets/Scripts/Bot/BotCombat.cs
Labels: bug, feature

#66 Add Health Bar for Crates
  Assets/Prefabs/Environment/Boost Crate.prefab
  Assets/Prefabs/Heroes/HealthBarGameUI.prefab
  Assets/Prefabs/Heroes/HealthBarGameUI.prefab.meta
  Assets/Scripts/Combat/Projectiles/Bomb.cs
  Assets/Scripts/Combat/Projectiles/Bullet.cs
Labels: feature

#68 Fix Crate Health Bar
  Assets/Prefabs/Environment/Boost Crate.prefab
  Assets/Prefabs/Heroes/Characters/Dinomike.prefab
  Assets/Prefabs/Heroes/Characters/Janet.prefab
Labels: bug

#70 Hero spawn place
  Assets/Scripts/Battlefield/BattleFieldBuilder.cs
  Assets/Scripts/Battlefield/BattleFieldGenerator.cs
  Assets/Scripts/Misc/ObjectsPool.cs
Labels: feature

#71 Add Scene Async Loading
  Assets/Prefabs/BattleField Builder.prefab
  Assets/Prefabs/Environment/Ground.prefab
  Assets/Prefabs/Environment/Wall.prefab
  Assets/Prefabs/Heroes/Characters/Player.prefab
  Assets/Scenes/BattleField.unity
  Assets/Scenes/CharacterChoice.unity
  Assets/Scripts/Battlefield/BattleFieldBuilder.cs
  Assets/Scripts/Battlefield/NavMeshSurfaceExtensions.cs
  Assets/Scripts/Battlefield/NavMeshSurfaceExtensions.cs.meta
  Assets/Scripts/CharacterSelection/CharacterSelector.cs
  Assets/Scripts/Hud/HealthBar.cs
Labels: bug

#72 Fix Bomb Material Color
  Assets/Models/Materials/bomb.mat
Labels: bug

#74 Hotfix Health Bar Rotation
  Assets/Prefabs/Heroes/HealthBarGameUI.prefab
Labels: bug
